### ISSUE TITLE
Could I please be added as maintainer here?

### ISSUE THREAD

**Issue by valeriupredoi** [conda-forge/esgf-pyclient-feedstock#20]
Hey folks @conda-forge/esgf-pyclient  - could I please be added as maintainer of this repo? I maintain a bunch of other Python packages, and this particular one would be useful for us since we use it in both ESMValTool and ESMValCore. Very many thanks in advance! Cheers :beer:

**Comment by cehbrecht** [comment]
done by #23. Thanks for joining :)

**Comment by valeriupredoi** [comment]
Carsten, good to see you around here, and many thanks for adding me, mate :beer:
